# Generated by Django 4.2.23 on 2026-09-22 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DetectionRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="uploads/%Y%m%d/", verbose_name="原图"),
                ),
                (
                    "original_name",
                    models.CharField(max_length=255, verbose_name="原始文件名"),
                ),
                ("conf_threshold", models.FloatField(verbose_name="置信度阈值")),
                (
                    "models_used",
                    models.CharField(
                        choices=[
                            ("ssd", "SSDLite-MobileNetV3"),
                            ("yolo", "YOLOv5s"),
                            ("both", "双模型对比"),
                        ],
                        default="both",
                        max_length=8,
                        verbose_name="使用模型",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="检测时间"
                    ),
                ),
            ],
            options={
                "verbose_name": "检测记录",
                "verbose_name_plural": "检测记录",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DetectionResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model_name", models.CharField(max_length=16, verbose_name="模型名")),
                (
                    "result_image",
                    models.ImageField(
                        upload_to="results/%Y%m%d/", verbose_name="结果图"
                    ),
                ),
                (
                    "num_objects",
                    models.IntegerField(default=0, verbose_name="检测目标数"),
                ),
                (
                    "inference_ms",
                    models.FloatField(default=0, verbose_name="推理耗时(ms)"),
                ),
                ("detail", models.JSONField(default=list, verbose_name="检测明细")),
                (
                    "record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="detector.detectionrecord",
                        verbose_name="检测记录",
                    ),
                ),
            ],
            options={
                "verbose_name": "检测结果",
                "verbose_name_plural": "检测结果",
            },
        ),
    ]
