# Generated by Django 4.2.23 on 2026-09-22 03:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("detector", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="detectionrecord",
            name="user",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="detectionrecord",
                to=settings.AUTH_USER_MODEL,
                verbose_name="检测用户",
            ),
        ),
    ]
