# Generated by Django 4.2.23 on 2026-09-27 02:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("detector", "0002_detectionrecord_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="detectionrecord",
            name="models_used",
            field=models.CharField(
                choices=[
                    ("yolov8", "YOLOv8s"),
                    ("yolov8n", "YOLOv8n"),
                    ("yolo", "YOLOv5s"),
                    ("yolov5n", "YOLOv5n"),
                    ("both", "双模型对比(s)"),
                    ("nano", "双模型对比(n)"),
                    ("all", "四模型全对比"),
                ],
                default="both",
                max_length=8,
                verbose_name="使用模型",
            ),
        ),
        migrations.CreateModel(
            name="VideoRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[("upload", "上传视频"), ("camera", "摄像头实时")],
                        default="upload",
                        max_length=10,
                        verbose_name="来源",
                    ),
                ),
                (
                    "video_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="videos/%Y%m%d/",
                        verbose_name="原视频",
                    ),
                ),
                (
                    "result_video",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="videos/results/%Y%m%d/",
                        verbose_name="检测后视频",
                    ),
                ),
                (
                    "original_name",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="原始文件名",
                    ),
                ),
                ("conf_threshold", models.FloatField(verbose_name="置信度阈值")),
                (
                    "models_used",
                    models.CharField(
                        default="both", max_length=8, verbose_name="使用模型"
                    ),
                ),
                ("fps", models.FloatField(default=0, verbose_name="视频帧率")),
                ("total_frames", models.IntegerField(default=0, verbose_name="总帧数")),
                (
                    "processed_frames",
                    models.IntegerField(default=0, verbose_name="已处理帧数"),
                ),
                (
                    "total_objects",
                    models.IntegerField(default=0, verbose_name="检测目标总数"),
                ),
                (
                    "avg_objects_per_frame",
                    models.FloatField(default=0, verbose_name="平均每帧目标数"),
                ),
                (
                    "duration_sec",
                    models.FloatField(default=0, verbose_name="视频时长(秒)"),
                ),
                (
                    "inference_ms_avg",
                    models.FloatField(default=0, verbose_name="平均单帧推理耗时(ms)"),
                ),
                (
                    "status",
                    models.CharField(
                        default="processing", max_length=10, verbose_name="状态"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "finished_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="完成时间"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="videorecord",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="检测用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "视频检测记录",
                "verbose_name_plural": "视频检测记录",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("image", "图片检测统计"),
                            ("video", "视频检测统计"),
                            ("combined", "综合统计"),
                        ],
                        default="combined",
                        max_length=10,
                        verbose_name="报表类型",
                    ),
                ),
                (
                    "file_format",
                    models.CharField(
                        choices=[("pdf", "PDF"), ("excel", "Excel")],
                        default="pdf",
                        max_length=10,
                        verbose_name="文件格式",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="reports/%Y%m%d/", verbose_name="报表文件"
                    ),
                ),
                (
                    "date_from",
                    models.DateField(blank=True, null=True, verbose_name="起始日期"),
                ),
                (
                    "date_to",
                    models.DateField(blank=True, null=True, verbose_name="结束日期"),
                ),
                (
                    "model_filter",
                    models.CharField(
                        blank=True, default="", max_length=20, verbose_name="模型筛选"
                    ),
                ),
                ("summary", models.JSONField(default=dict, verbose_name="统计摘要")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="生成时间"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="生成用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "统计报表",
                "verbose_name_plural": "统计报表",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VideoFrameResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("frame_index", models.IntegerField(verbose_name="帧序号")),
                ("model_name", models.CharField(max_length=16, verbose_name="模型名")),
                ("num_objects", models.IntegerField(default=0, verbose_name="目标数")),
                (
                    "inference_ms",
                    models.FloatField(default=0, verbose_name="推理耗时(ms)"),
                ),
                ("detail", models.JSONField(default=list, verbose_name="检测明细")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="frames",
                        to="detector.videorecord",
                        verbose_name="视频记录",
                    ),
                ),
            ],
            options={
                "verbose_name": "视频帧结果",
                "verbose_name_plural": "视频帧结果",
                "ordering": ["frame_index"],
                "indexes": [
                    models.Index(
                        fields=["record", "frame_index"],
                        name="detector_vi_record__33c34d_idx",
                    )
                ],
            },
        ),
    ]
